### ISSUE TITLE
OSError: [Errno 101] Network is unreachable - ipv6 related

### ISSUE THREAD

**Issue by 037g** [Comcast/connvitals#10]
OS: Ubuntu(18.08 LTS) or OSX 11.2.3
Installed via pip3. (Python 3.7.3)

I get the same behavior on both systems. Appreciate any help you can provide.

`connvitals -t domain.com
Traceback (most recent call last):
  File "/home/arctiqleo/.local/bin/connvitals", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/connvitals/__init__.py", line 51, in main
    from . import collector
  File "/usr/local/lib/python3.7/dist-packages/connvitals/collector.py", line 19, in <module>
    from . import utils, config, ping, traceroute, ports
  File "/usr/local/lib/python3.7/dist-packages/connvitals/ping.py", line 26, in <module>
    from . import icmp
  File "/usr/local/lib/python3.7/dist-packages/connvitals/icmp.py", line 31, in <module>
    s.connect(("2001:4998:c:1023::4", 1)) #yahoo.com public IPv6 address
OSError: [Errno 101] Network is unreachable`

**Comment by ocket8888** [comment]
That error is coming from your operating system. I would suspect that your network interface doesn't support IPv6 - does that sound right? Can you run `ping 2001:4998:44:3507::8001`?
